my_dagster_snowflake_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: PHWYUBU-GR70594
      user: KPAWAR9428
      authenticator: externalbrowser
      role: ACCOUNTADMIN
      database: DBT_SNF
      warehouse: COMPUTE_WH
      schema: DBT_SNF_SC
      threads: 4
      client_session_keep_alive: False
      query_tag: dbt-dagster