name: Deploy to Dagster+

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  dagster_cloud_deploy:
    runs-on: ubuntu-latest
    name: Dagster+ Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Dagster+
        uses: dagster-io/dagster-cloud-action/actions/deploy@v0.1
        with:
          dagster_cloud_api_token: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
          location: ${{ matrix.location }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        location:
          - my_dagster_project